made fixes to scoring loop, updates to todo and added some multiplayer functionality

diff --git a/src/scoring_loop b/src/scoring_loop
--- a/src/scoring_loop
+++ b/src/scoring_loop
@@ -44,7 +44,7 @@ while [ 0 ]; do
 
     LINES_READ_IN_OUT=$(expr $LINES_READ_IN_OUT + 1)
     # check if the scorebot has been signaled to stop
-    if [ "$(sed -n "$LINES_READ_IN_OUT p" $INPT_OUTPT_FILE)" == "game completed" ]; then
+    if [ "$(sed -n "$LINES_READ_IN_OUT p" $INPT_OUTPT_FILE)" = "game completed" ]; then
 
       exit
 
@@ -64,7 +64,7 @@ while [ 0 ]; do
     # find out what the points are currently, if there isn't any points in
     # /tmp/scoring/answers then assign zero to each team, if there is then get
     # the most current points acquired 
-    if [ "$LINES_IN_HEADER" == "$(wc -l $SCOREBOARD_FILE | awk '{print $(NF - 1)}')" ]; then
+    if [ "$LINES_IN_HEADER" = "$(wc -l $SCOREBOARD_FILE | awk '{print $(NF - 1)}')" ]; then
         DEFENDING_PTS="0"
         ATTACKING_PTS="0"
     else
@@ -75,28 +75,28 @@ while [ 0 ]; do
     NOW=$(date +%m/%d/%y**%H:%M:%S)
     PRETTY_INPUT="$(blacklist_replace "$INPUT")"
     # if the refcalc output and the given output are the same, award appropriate points
-    if [ $(equal "$REFCALC_OUTPUT" "$OUTPUT" 2> $ERRLOG) == "True" ]; then
+    if [ $(equal "$REFCALC_OUTPUT" "$OUTPUT" 2> $ERRLOG) = "True" ]; then
 
       # defending team gets points and attacking team gets no points
       DEFENDING_PTS="$(echo "$DEFENDING_PTS + 10" | $REFCALC)"
       print_score
 
     # else if both the refcalc and the defending team gave errors, defending team gets pts
-    elif [[ "$REFCALC_STDERR" != "" && $(echo "$OUTPUT" | grep -q -i "error"; echo $?) == "0" ]]; then
+    elif [[ "$REFCALC_STDERR" != "" && $(echo "$OUTPUT" | grep -q -i "error"; echo $?) = "0" ]]; then
 
       # defending team gets points and attacking team gets no points
       DEFENDING_PTS="$(echo "$DEFENDING_PTS + 10" | $REFCALC)"
       print_score
 
     # else if the given output is a crash
-    elif [ "$(echo $MOST_RECENT_LINE | awk -F: '{print $(NF - 1)}')" == "1" ]; then
+    elif [ "$(echo $MOST_RECENT_LINE | awk -F: '{print $(NF - 1)}')" = "1" ]; then
 
       # attacking team gets 50pts
       ATTACKING_PTS="$(echo "$ATTACKING_PTS + 50" | $REFCALC)"
       print_score
 
     # else if the refcalc output and the defending team's output are unequal, award appropriate points
-    elif [[ $(equal "$OUTPUT" "$REFCALC_OUTPUT" 2> $ERRLOG) == "False" || "" == $OUTPUT ]]; then
+    elif [[ $(equal "$OUTPUT" "$REFCALC_OUTPUT" 2> $ERRLOG) = "False" || "" = $OUTPUT ]]; then
 
 
       # defending team gets no points and attacking team gets 10 pts
